### ISSUE TITLE
res <- pbDS(pb, verbose = FALSE) Error in x[[1]] : subscript out of bounds

### ISSUE THREAD

**Issue by Jungkooklove0901** [HelenaLC/muscat#116] opened 2022-12-29 01:39 UTC
I ran res <- pbDS(pb, verbose = FALSE) and got the following error.
Error in x[[1]] : subscript out of bounds

How should I solve it?

**Comment by HelenaLC** [comment] 2023-01-03 18:04
As with any issues anywhere on GitHub, **please post the output of your `sessionInfo()`** so we can rule out package version- and/or dependency related issues. Also, please post and explain in more detail the code leading up to this point. The above is hardly reproducible and it is difficult (impossible, really) for me to help/advise given such little information.

**Comment by Jungkooklove0901** [comment] 2023-01-04 00:49
Thank you for your answer.
Does the method use "edgeR", "DESeq2", "limma-trend", "limma-voom" have a significant impact on the result value?

**Comment by HelenaLC** [comment] 2023-01-04 12:34
...closing due to insufficient information and non-responsiveness to above request. Happy to help out, discuss more etc. if more detail is provided.

**Closed by HelenaLC** 2023-01-04 12:34 UTC
